### ISSUE TITLE
audiodec model downloaded from voidful/Audiodec has import error in dataset creator

### ISSUE THREAD

**Issue by dlion168** [voidful/Codec-SUPERB#17]
I follow the exception message to 
`pip install git+https://github.com/voidful/AudioDec.git`
But there seem to have import errors.
Error message:
```
Synthesizing dataset with audiodec_24k_320d
Traceback (most recent call last):
  File "~/Codec-SUPERB/codec/audiodec_24k_320d.py", line 9, in config
    from AudioDec.utils.audiodec import AudioDec as AudioDecModel, assign_model
  File "~/.local/lib/python3.10/site-packages/AudioDec/utils/audiodec.py", line 15, in <module>
    from AudioDec.models.vocoder.HiFiGAN import StreamGenerator as generator_hifigan
  File "~/.local/lib/python3.10/site-packages/AudioDec/models/vocoder/HiFiGAN.py", line 24, in <module>
    from AudioDec.models.vocoder.modules.discriminator import HiFiGANMultiScaleDiscriminator
  File "~/.local/lib/python3.10/site-packages/AudioDec/models/vocoder/modules/discriminator.py", line 24, in <module>
    from layers.conv_layer import NonCausalConv1d, NonCausalConv2d
ModuleNotFoundError: No module named 'layers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Codec-SUPERB/dataset_creator.py", line 73, in <module>
    run_experiment(args.dataset)
  File "~/Codec-SUPERB/dataset_creator.py", line 33, in run_experiment
    codec = load_codec(codec_name)
  File "~/Codec-SUPERB/codec/__init__.py", line 6, in load_codec
    return module.Codec()
  File "~/Codec-SUPERB/base_codec/audiodec.py", line 9, in __init__
    self.config()
  File "~/Codec-SUPERB/codec/audiodec_24k_320d.py", line 11, in config
    raise Exception("Please install AudioDec first. pip install git+https://github.com/voidful/AudioDec.git")
```

**Comment by voidful** [comment]
Fixed Here: https://github.com/voidful/AudioDec/commit/290173894ab3066e44be39b289af8bca7202f06a
